
package it.unibo.test.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2018-10-08T22:52:10.431+02:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "Exception", targetNamespace = "http://services.unibo.it/")
public class Exception_Exception extends java.lang.Exception {
    
    private it.unibo.test.services.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, it.unibo.test.services.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, it.unibo.test.services.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public it.unibo.test.services.Exception getFaultInfo() {
        return this.exception;
    }
}
