package it.unibo.test.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2018-10-08T22:52:10.446+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://services.unibo.it/", name = "UniboServices")
@XmlSeeAlso({ObjectFactory.class})
public interface UniboServices {

    @WebMethod
    @RequestWrapper(localName = "deletCredentialsFromIdUser", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.DeletCredentialsFromIdUser")
    @ResponseWrapper(localName = "deletCredentialsFromIdUserResponse", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.DeletCredentialsFromIdUserResponse")
    public void deletCredentialsFromIdUser(
        @WebParam(name = "idUser", targetNamespace = "")
        int idUser
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getUser", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.GetUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.unibo.test.services.UserBean getUser(
        @WebParam(name = "idUser", targetNamespace = "")
        java.lang.Integer idUser
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.AddUserResponse")
    public void addUser(
        @WebParam(name = "idUser", targetNamespace = "")
        it.unibo.test.services.UserBean idUser
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "addCredentials", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.AddCredentials")
    @ResponseWrapper(localName = "addCredentialsResponse", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.AddCredentialsResponse")
    public void addCredentials(
        @WebParam(name = "idUser", targetNamespace = "")
        java.lang.Integer idUser,
        @WebParam(name = "cred", targetNamespace = "")
        it.unibo.test.services.CredentialBean cred
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCredential", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.GetCredential")
    @ResponseWrapper(localName = "getCredentialResponse", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.GetCredentialResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.unibo.test.services.CredentialBean getCredential(
        @WebParam(name = "idUser", targetNamespace = "")
        java.lang.Integer idUser
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.DeleteUserResponse")
    public void deleteUser(
        @WebParam(name = "idUser", targetNamespace = "")
        int idUser
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "deletCredentialsFromId", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.DeletCredentialsFromId")
    @ResponseWrapper(localName = "deletCredentialsFromIdResponse", targetNamespace = "http://services.unibo.it/", className = "it.unibo.test.services.DeletCredentialsFromIdResponse")
    public void deletCredentialsFromId(
        @WebParam(name = "idUser", targetNamespace = "")
        int idUser
    ) throws Exception_Exception;
}
